// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVHHZVXgUci-datgH3DYz6cWi3CSxntjU',
    appId: '1:812484695833:web:0ac4c4b92b2943d5f49788',
    messagingSenderId: '812484695833',
    projectId: 'pagaoa-advmobprog',
    authDomain: 'pagaoa-advmobprog.firebaseapp.com',
    storageBucket: 'pagaoa-advmobprog.firebasestorage.app',
    measurementId: 'G-WHM8JDJK7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB04tbZWmuGDsbvoiMgRySmqhMDefysiIQ',
    appId: '1:812484695833:android:4f473c2647a304d4f49788',
    messagingSenderId: '812484695833',
    projectId: 'pagaoa-advmobprog',
    storageBucket: 'pagaoa-advmobprog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk3v02UpIcRNazJxWcgs5VWDwQ61wabyk',
    appId: '1:812484695833:ios:feb26d13a41ce1c5f49788',
    messagingSenderId: '812484695833',
    projectId: 'pagaoa-advmobprog',
    storageBucket: 'pagaoa-advmobprog.firebasestorage.app',
    iosBundleId: 'com.example.pagaoaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVHHZVXgUci-datgH3DYz6cWi3CSxntjU',
    appId: '1:812484695833:web:a675de808e2a6c55f49788',
    messagingSenderId: '812484695833',
    projectId: 'pagaoa-advmobprog',
    authDomain: 'pagaoa-advmobprog.firebaseapp.com',
    storageBucket: 'pagaoa-advmobprog.firebasestorage.app',
    measurementId: 'G-2M6KR4GNET',
  );
}
